// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCel2a1uCzAuLfjlpAN28HXlZn-CAz1eH8',
    appId: '1:739618848459:web:64a20bf2d31279a1b5a54e',
    messagingSenderId: '739618848459',
    projectId: 'shineweb-e2a3b',
    authDomain: 'shineweb-e2a3b.firebaseapp.com',
    storageBucket: 'shineweb-e2a3b.appspot.com',
    measurementId: 'G-X0VJKFQLTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6N61c6LmC3Yhp1pGJ6uWS2Cwn8enLrfM',
    appId: '1:739618848459:android:0736bbbc115125d2b5a54e',
    messagingSenderId: '739618848459',
    projectId: 'shineweb-e2a3b',
    storageBucket: 'shineweb-e2a3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQvPGU_hsL-tu-kfp8qCyDD_uvIdNaLnw',
    appId: '1:739618848459:ios:701a647f0a4b485eb5a54e',
    messagingSenderId: '739618848459',
    projectId: 'shineweb-e2a3b',
    storageBucket: 'shineweb-e2a3b.appspot.com',
    iosClientId: '739618848459-15gjaf36m580er9nqvi612epmaiq6g7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.shineweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQvPGU_hsL-tu-kfp8qCyDD_uvIdNaLnw',
    appId: '1:739618848459:ios:f06508675d143b81b5a54e',
    messagingSenderId: '739618848459',
    projectId: 'shineweb-e2a3b',
    storageBucket: 'shineweb-e2a3b.appspot.com',
    iosClientId: '739618848459-aui02c2fdnqc58ur12357r3hjujv1dve.apps.googleusercontent.com',
    iosBundleId: 'com.example.shineweb.RunnerTests',
  );
}
